Repository tchupp/actions-detect-directory-changes, pull requests merged in 2023-08, with the labels that each got.

#9 feat: provide a way to return all included paths based on specific directories changing
  README.md
  action.yml
  src/filter-files.test.ts
  src/filter-files.ts
  src/index.ts
Labels: feature, docs

#10 feat: auto-release major version
  .github/release-drafter.yml
Labels: feature, major

#11 chore: Update release tagger to consider created releases
  .github/workflows/release-tagger.yml
Labels: chore

#12 docs: add 'with' to action invocation
  README.md
Labels: docs
